### ISSUE TITLE
How to define as_indexed_json with model associations ?

### ISSUE THREAD

**Issue by pierrax** [kentaroi/elasticsearch-model-globalize#1]
Hi,

I have two classes `Center` (no translation) and `City` (titles translated).
And I would like to search in the center names but also in the translated city names.

``` ruby
class Center < ActiveRecord::Base
  belongs_to: :city

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^10', 'title']
          }
        }
      }
    )
  end

  def as_indexed_json(options={})
    as_json(only: 'name',  
                  include: { city: { only: [:title_fr, :title_en, :title] }
                  }
    )
  end
  ...  
end
```

and the City.rb

``` ruby
class City < ActiveRecord::Base
  has_many: :centers
  translates :title

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Elasticsearch::Model::Globalize::MultipleFields

  mapping do
    indexes :id,             type: 'integer'
    indexes :title_en,        analyzer: 'kuromoji'
    indexes :title_fr,        analyzer: 'snowball'
  end

  def as_indexed_json(options={})
    { id: id,
      title_en: title_en,
      title_fr: title_fr,
    }
  end
  ...
end
```

Unfortunately, this doesn't seems to work. 
In my center index, I only have the `title` and not the translations `title_fr'...

Any idea ?
Thanks !

**Comment by kentaroi** [comment]
Sorry for the late reply. I have struggled in my job.

I'm sorry I didn't care about `include` when implementing this gem.
I don't have enough time for OSS right now, but I will find time and look into this problem when possible.
Pull requests are always welcome.

**Comment by alepore** [comment]
@pierrax not sure if it's related, have you tried adding https://github.com/globalize/globalize-accessors ?
EDIT: oh i see this gem does similar things... not sure it will work

**Comment by kentaroi** [comment]
@pierrax 
I have not looked into this issue yet, but I want to clarify the problem.
First of all, `Elasticsearch::Model::MultipleFields` is not a module to use [`multi-fields`](http://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html) but to use multiple fields,
and you must specify each field, `'title_en', 'title_fr'`, or not specify any fields when searching.

Would you try this?:

``` ruby
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^10', 'title_en', 'title_fr']
          }
        }
      }
    )
  end
```
